### ISSUE TITLE
Cannot find jupyter hb port

### ISSUE THREAD

**Issue by junyi-hou** [jerry40/guile-kernel#9]
When I try to start guile kernel I had the following error
```
Backtrace:
           7 (apply-smob/1 #<catch-closure 7f6d9f6fbb80>)
In ice-9/boot-9.scm:
    705:2  6 (call-with-prompt _ _ #<procedure default-prompt-handler (k proc)>)
In ice-9/eval.scm:
    619:8  5 (_ #(#(#<directory (guile-user) 7f6d9f391140>)))
In ice-9/boot-9.scm:
   2312:4  4 (save-module-excursion _)
  3831:12  3 (_)
In /usr/share/jupyter/kernels/guile/guile-jupyter-kernel.scm:
    50:23  2 (_)
    44:96  1 (create-address #f)
In unknown file:
           0 (number->string #f #<undefined>)

ERROR: In procedure number->string:
In procedure number->string: Wrong type argument in position 1: #f
```

system info
```
guile-2.2.4
gulie-json-0.6.0
jupyter core 4.5.0
zeromq-4.3.2
```
with `gulie-simple-zmq` installed as instructed.

I am just starting to learn scheme so could not really help, but please let me know if you need more information. Thanks!

**Comment by jerry40** [comment]
Hi!
I think you're trying to run this kernel from the guile interpreter, but it should be started by the jupyter core. So you need to do setup steps described in the readme, run the jupyter notebook and choose 'Guile' somewhere in jupyter's menu.

**Comment by junyi-hou** [comment]
Thanks for the quick response!

No I wasn't trying to call guile-kernel from inside the guile. The command that produces the error is `jupyter console --kernel=guile` (jupyter notebook gives the same result). I truncated the backtrace message to only the relevant part. the whole backtrace also contains jupyter error (since it cannot find the kernel). The full backtrace is below
```
~/portage/dev-scheme/guile-simple-zmq $ jupyter console --kernel=guile
Backtrace:
           7 (apply-smob/1 #<catch-closure 7fe0a6b80280>)
In ice-9/boot-9.scm:
    705:2  6 (call-with-prompt _ _ #<procedure default-prompt-handler (k proc)>)
In ice-9/eval.scm:
    619:8  5 (_ #(#(#<directory (guile-user) 7fe0a6825140>)))
In ice-9/boot-9.scm:
   2312:4  4 (save-module-excursion _)
  3831:12  3 (_)
In /usr/share/jupyter/kernels/guile/guile-jupyter-kernel.scm:
    50:23  2 (_)
    44:96  1 (create-address #f)
In unknown file:
           0 (number->string #f #<undefined>)

ERROR: In procedure number->string:
In procedure number->string: Wrong type argument in position 1: #f
Traceback (most recent call last):
  File "/home/junyi/.local/bin/jupyter-console", line 10, in <module>
    sys.exit(main())
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/junyi/.local/lib64/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</home/junyi/.local/lib64/python3.6/site-packages/decorator.py:decorator-gen-117>", line 2, in initialize
  File "/home/junyi/.local/lib64/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_console/app.py", line 142, in initialize
    self.init_shell()
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_console/app.py", line 115, in init_shell
    confirm_exit=self.confirm_exit,
  File "/home/junyi/.local/lib64/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_console/ptshell.py", line 287, in __init__
    self.init_kernel_info()
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_console/ptshell.py", line 341, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_client/blocking/channels.py", line 50, in get_msg
    ready = self.socket.poll(timeout)
  File "/home/junyi/.local/lib64/python3.6/site-packages/zmq/sugar/socket.py", line 702, in poll
    evts = dict(p.poll(timeout))
  File "/home/junyi/.local/lib64/python3.6/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 143, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
  File "/home/junyi/.local/lib64/python3.6/site-packages/jupyter_console/app.py", line 124, in handle_sigint
    if self.shell._executing:
AttributeError: 'ZMQTerminalIPythonApp' object has no attribute 'shell'
```

**Comment by jerry40** [comment]
Hm... Can you paste your kernel.json file here?

**Comment by junyi-hou** [comment]
See below for information on `kernel.json` I install in `/usr/share/jupyter/kernels/` so I made the changes accordingly. I tried to copy `/src/*` to `$HOME/.local/share/jupyter/kernel/guile/` but I got the same error. 
```
/usr/share/jupyter/kernels/guile $ cat /usr/share/jupyter/kernels/guile/kernel.json
{
    "argv": ["guile", "-s",
             "/usr/share/jupyter/kernels/guile/guile-jupyter-kernel.scm",
             "--", "{connection_file}"],
    "display_name": "Guile",
    "language": "scheme"
}
```

**Comment by jerry40** [comment]
It is very strange... Like the jupyter's connection file does not contain
hb_port key. May you try to comment line 50 in guile-jupyter-kernel.scm? It
will lead to an error too, but it is interesting what error we'll get.

**Comment by junyi-hou** [comment]
when I did that, the very next line (51) error out with the same error:
```
Backtrace:
           7 (apply-smob/1 #<catch-closure 7f911cc65000>)
In ice-9/boot-9.scm:
    705:2  6 (call-with-prompt _ _ #<procedure default-prompt-handler (k proc)>)
In ice-9/eval.scm:
    619:8  5 (_ #(#(#<directory (guile-user) 7f911c8e7140>)))
In ice-9/boot-9.scm:
   2312:4  4 (save-module-excursion _)
  3831:12  3 (_)
In /usr/share/jupyter/kernels/guile/guile-jupyter-kernel.scm:
    51:23  2 (_)
    44:96  1 (create-address #f)
In unknown file:
           0 (number->string #f #<undefined>)

ERROR: In procedure number->string:
In procedure number->string: Wrong type argument in position 1: #f
```

I feel like guile is not really getting any information from jupyter's connection file.

**Comment by jerry40** [comment]
Yes, it opens the file but strangely does not find the info there.. May it
be connected with the network setup? It would be interesting to have a look
at that connection file, I think it is possible to get it, we can print it
from the guile code at least. I am away from my PC at the moment though.
Let me think about it tomorrow and get back to you. Unusual problem, but I
believe we can fix it.

**Comment by junyi-hou** [comment]
Same error, but I can confirm that the connection file seems all good:
```
~ $ jupyter kernel --kernel=guile
[KernelApp] Starting kernel 'guile'
[KernelApp] Connection file: /home/junyi/.local/share/jupyter/runtime/kernel-d9ddfb0d-4f3b-41ae-a8ec-5ae670a707a5.json
[KernelApp] To connect a client: --existing kernel-d9ddfb0d-4f3b-41ae-a8ec-5ae670a707a5.json
Backtrace:
           7 (apply-smob/1 #<catch-closure 7f69f90d7280>)
In ice-9/boot-9.scm:
    705:2  6 (call-with-prompt _ _ #<procedure default-prompt-handler (k proc)>)
In ice-9/eval.scm:
    619:8  5 (_ #(#(#<directory (guile-user) 7f69f8d7c140>)))
In ice-9/boot-9.scm:
   2312:4  4 (save-module-excursion _)
  3831:12  3 (_)
In /usr/share/jupyter/kernels/guile/guile-jupyter-kernel.scm:
    50:23  2 (_)
    44:96  1 (create-address #f)
In unknown file:
           0 (number->string #f #<undefined>)

ERROR: In procedure number->string:
In procedure number->string: Wrong type argument in position 1: #f
```

```
~/.local/share/jupyter/runtime $ cat kernel-d9ddfb0d-4f3b-41ae-a8ec-5ae670a707a5.json 
{
  "shell_port": 47693,
  "iopub_port": 52295,
  "stdin_port": 54619,
  "control_port": 47939,
  "hb_port": 50737,
  "ip": "127.0.0.1",
  "key": "346fd226-6aa7c32c5755a8129e50bd80",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "guile"
}~/.local/share/jupyter/runtime $ 
```

**Comment by jerry40** [comment]
I found the reason - recently we've committed changes regarding usage of newer versions of guile-json but I forgot to mention this in the readme, let's try using guile-json-3.2.0 (see the readme change please)

**Comment by jerry40** [comment]
BTW, I added a dockerfile so you can try building an image and running a container
```
sudo docker build -t epanfilov/guile-kernel .
sudo docker run epanfilov/guile-kernel
```

**Comment by junyi-hou** [comment]
Thank you for the quick response! I can confirm updating `guile-json` solves the problem.

I am not familiar with docker so I wrote a few ebuilds to automatically build `guile-kernel` on gentoo. I put the scripts [here](https://github.com/junyi-hou/my-overlay) in case someone needs it in the future.

Thank!

**Comment by jerry40** [comment]
Thanks!
